IF OBJECT_ID('SP_ABONOS_CREATE') IS NOT NULL
BEGIN 
DROP PROC SP_ABONOS_CREATE 
END
GO
CREATE PROCEDURE SP_ABONOS_CREATE
  @CODIGO_ABONO NUMERIC(12),
  @NUMERO_CUENTA NUMERIC(12),
  @FECHA_ABONADO DATE,
  @MONTO FLOAT,
  @COMENTARIO VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS
BEGIN
INSERT INTO ABONOS  (
    CODIGO_ABONO,
    NUMERO_CUENTA,
    FECHA_ABONADO,
    MONTO,
    COMENTARIO,
	  FECHA_CREACION,
    FECHA_ACTUALIZACION,
    USUARIO_CREADOR, 
    USUARIO_ACTUALIZACION)
  VALUES (
    @CODIGO_ABONO,
    @NUMERO_CUENTA,
    @FECHA_ABONADO,
    @MONTO,
    @COMENTARIO,
    @FECHA_CREACION,
    @FECHA_ACTUALIZACION,
    @USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION)
      
SELECT 
	  @NUMERO_CUENTA = NUMERO_CUENTA,
    @FECHA_ABONADO = FECHA_ABONADO,
    @MONTO = MONTO,
    @COMENTARIO = COMENTARIO,
	  @FECHA_CREACION = FECHA_CREACION,
    @FECHA_ACTUALIZACION = FECHA_ACTUALIZACION,
    @USUARIO_CREADOR = USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION = USUARIO_ACTUALIZACION
FROM ABONOS 
WHERE  CODIGO_ABONO = @CODIGO_ABONO
END


------------------------------DELETE
IF OBJECT_ID('SP_ABONOS_DELETE') IS NOT NULL
BEGIN 
DROP PROC SP_ABONOS_DELETE
END 
GO
CREATE PROC SP_ABONOS_DELETE 
    @CODIGO_ABONO NUMERIC
AS 
BEGIN 
DELETE
FROM   ABONOS
WHERE  CODIGO_ABONO = @CODIGO_ABONO
 
END
GO


---------------------------------READ
IF OBJECT_ID('SP_ABONOS_READ') IS NOT NULL
BEGIN 
    DROP PROC SP_ABONOS_READ
END 
GO
CREATE PROC SP_ABONOS_READ
    @CODIGO_ABONO NUMERIC
AS 
BEGIN 
 
    SELECT CODIGO_ABONO, NUMERO_CUENTA, FECHA_ABONADO, MONTO, COMENTARIO, FECHA_CREACION, FECHA_ACTUALIZACION, USUARIO_CREADOR, USUARIO_ACTUALIZACION
    FROM   ABONOS 
    WHERE  (CODIGO_ABONO = @CODIGO_ABONO) 
END
GO

-------------------------------UPDATE
IF OBJECT_ID('SP_ABONOS_UPDATE') IS NOT NULL
BEGIN 
DROP PROC SP_ABONOS_UPDATE
END 
GO
CREATE PROC SP_ABONOS_UPDATE
  @CODIGO_ABONO NUMERIC(12),
  @NUMERO_CUENTA NUMERIC(12),
  @FECHA_ABONADO DATE,
  @MONTO FLOAT,
  @COMENTARIO VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS 
BEGIN 
 
UPDATE ABONOS
SET 
    NUMERO_CUENTA = @NUMERO_CUENTA,
    FECHA_ABONADO = @FECHA_ABONADO,
    MONTO = @MONTO,
    COMENTARIO = @COMENTARIO,
	  FECHA_CREACION = @FECHA_CREACION,
    FECHA_ACTUALIZACION = @FECHA_ACTUALIZACION,
    USUARIO_CREADOR = @USUARIO_CREADOR,
    USUARIO_ACTUALIZACION = @USUARIO_ACTUALIZACION
WHERE CODIGO_ABONO = @CODIGO_ABONO
END
GO