IF OBJECT_ID('SP_PAGOS_CREATE') IS NOT NULL
BEGIN 
DROP PROC SP_PAGOS_CREATE 
END
GO
CREATE PROCEDURE SP_PAGOS_CREATE
  @NUMERO_PAGO NUMERIC(12),
  @NUMERO_PRESTAMO NUMERIC(12),
  @FECHA DATE,
  @MONTO FLOAT,
  @INTERESES_PAGADOS FLOAT,
  @CAPITAL_PAGADOS FLOAT,
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS
BEGIN
INSERT INTO PAGOS  (
    NUMERO_PAGO,
    NUMERO_PRESTAMO,
    FECHA,
    MONTO,
    INTERESES_PAGADOS,
    CAPITAL_PAGADOS,
	  FECHA_CREACION,
    FECHA_ACTUALIZACION,
    USUARIO_CREADOR,
    USUARIO_ACTUALIZACION)
  VALUES (
    @NUMERO_PAGO,
    @NUMERO_PRESTAMO,
    @FECHA,
    @MONTO,
    @INTERESES_PAGADOS,
    @CAPITAL_PAGADOS,
    @FECHA_CREACION,
    @FECHA_ACTUALIZACION,
    @USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION)
      
SELECT 
	  @NUMERO_PRESTAMO = NUMERO_PRESTAMO,
    @FECHA = FECHA,
    @MONTO = MONTO,
    @INTERESES_PAGADOS = INTERESES_PAGADOS,
    @CAPITAL_PAGADOS = CAPITAL_PAGADOS,
	  @FECHA_CREACION = FECHA_CREACION,
    @FECHA_ACTUALIZACION = FECHA_ACTUALIZACION,
    @USUARIO_CREADOR = USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION = USUARIO_ACTUALIZACION
FROM PAGOS 
WHERE  NUMERO_PAGO = @NUMERO_PAGO
END


------------------------------DELETE
IF OBJECT_ID('SP_PAGOS_DELETE') IS NOT NULL
BEGIN 
DROP PROC SP_PAGOS_DELETE
END 
GO
CREATE PROC SP_PAGOS_DELETE 
    @NUMERO_PAGO NUMERIC
AS 
BEGIN 
DELETE
FROM   PAGOS
WHERE  NUMERO_PAGO = @NUMERO_PAGO
 
END
GO


---------------------------------READ
IF OBJECT_ID('SP_PAGOS_READ') IS NOT NULL
BEGIN 
    DROP PROC SP_PAGOS_READ
END 
GO
CREATE PROC SP_PAGOS_READ
    @NUMERO_PAGO NUMERIC
AS 
BEGIN 
 
    SELECT NUMERO_PAGO, NUMERO_PRESTAMO, FECHA, MONTO, INTERESES_PAGADOS, CAPITAL_PAGADOS, FECHA_CREACION, FECHA_ACTUALIZACION, USUARIO_CREADOR, USUARIO_ACTUALIZACION
    FROM   PAGOS 
    WHERE  (NUMERO_PAGO = @NUMERO_PAGO) 
END
GO

-------------------------------UPDATE
IF OBJECT_ID('SP_PAGOS_UPDATE') IS NOT NULL
BEGIN 
DROP PROC SP_PAGOS_UPDATE
END 
GO
CREATE PROC SP_PAGOS_UPDATE
  @NUMERO_PAGO NUMERIC(12),
  @NUMERO_PRESTAMO NUMERIC(12),
  @FECHA DATE,
  @MONTO FLOAT,
  @INTERESES_PAGADOS FLOAT,
  @CAPITAL_PAGADOS FLOAT,
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS 
BEGIN 
 
UPDATE PAGOS
SET 
    NUMERO_PRESTAMO = @NUMERO_PRESTAMO,
    FECHA = @FECHA,
    MONTO = @MONTO,
    INTERESES_PAGADOS = @INTERESES_PAGADOS,
    CAPITAL_PAGADOS = @CAPITAL_PAGADOS,
	  FECHA_CREACION = @FECHA_CREACION,
    FECHA_ACTUALIZACION = @FECHA_ACTUALIZACION,
    USUARIO_CREADOR = @USUARIO_CREADOR,
    USUARIO_ACTUALIZACION = @USUARIO_ACTUALIZACION
WHERE  NUMERO_PAGO = @NUMERO_PAGO
END
GO