IF OBJECT_ID('SP_PERSONA_EXTERNAS_CREATE') IS NOT NULL
BEGIN 
DROP PROC SP_PERSONA_EXTERNAS_CREATE 
END
GO
CREATE PROCEDURE SP_PERSONA_EXTERNAS_CREATE
  @CODIGO_PERSONA_EXTERNA NUMERIC(12),
  @PRIMER_NOMBRE VARCHAR(100),
  @SEGUNDO_NOMBRE VARCHAR(100),
  @PRIMER_APELLIDO VARCHAR(100),
  @SEGUNDO_APELLIDO VARCHAR(100),
  @PARENTESCO_AVAL VARCHAR(100),
  @DIRECCION VARCHAR(100),
  @FECHA_NACIMIENTO DATE,
  @CORREO_PRIMARIO VARCHAR(100),
  @CORREO_SECUNDARIO VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS
BEGIN
INSERT INTO PERSONA_EXTERNA  (
    CODIGO_PERSONA_EXTERNA,
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    PARENTESCO_AVAL,
    DIRECCION,
    FECHA_NACIMIENTO,
    CORREO_PRIMARIO,
    CORREO_SECUNDARIO,
	  FECHA_CREACION,
    FECHA_ACTUALIZACION,
    USUARIO_CREADOR,
    USUARIO_ACTUALIZACION)
  VALUES (
    @CODIGO_PERSONA_EXTERNA,
    @PRIMER_NOMBRE,
    @SEGUNDO_NOMBRE,
    @PRIMER_APELLIDO,
    @SEGUNDO_APELLIDO,
    @PARENTESCO_AVAL,
    @DIRECCION,
    @FECHA_NACIMIENTO,
    @CORREO_PRIMARIO,
    @CORREO_SECUNDARIO,
    @FECHA_CREACION,
    @FECHA_ACTUALIZACION,
    @USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION)
      
SELECT 
    @PRIMER_NOMBRE = PRIMER_NOMBRE,
    @SEGUNDO_NOMBRE = SEGUNDO_NOMBRE,
    @PRIMER_APELLIDO = PRIMER_APELLIDO,
    @SEGUNDO_APELLIDO = SEGUNDO_APELLIDO,
    @PARENTESCO_AVAL = PARENTESCO_AVAL,
    @DIRECCION = DIRECCION,
    @FECHA_NACIMIENTO = FECHA_NACIMIENTO,
    @CORREO_PRIMARIO = CORREO_PRIMARIO,
    @CORREO_SECUNDARIO = CORREO_SECUNDARIO,
	  @FECHA_CREACION = FECHA_CREACION,
    @FECHA_ACTUALIZACION = FECHA_ACTUALIZACION,
    @USUARIO_CREADOR = USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION = USUARIO_ACTUALIZACION
FROM PERSONA_EXTERNA 
WHERE  CODIGO_PERSONA_EXTERNA = @CODIGO_PERSONA_EXTERNA
END


------------------------------DELETE
IF OBJECT_ID('SP_EMPLEADOS_DELETE') IS NOT NULL
BEGIN 
DROP PROC SP_EMPLEADOS_DELETE
END 
GO
CREATE PROC SP_EMPLEADOS_DELETE 
    @ID_EMPLEADO NUMERIC
AS 
BEGIN 
DELETE
FROM   EMPLEADO
WHERE  ID_EMPLEADO = @ID_EMPLEADO
 
END
GO


---------------------------------READ
IF OBJECT_ID('SP_EMPLEADOS_READ') IS NOT NULL
BEGIN 
    DROP PROC SP_EMPLEADOS_READ
END 
GO
CREATE PROC SP_EMPLEADOS_READ
    @ID_EMPLEADO NUMERIC
AS 
BEGIN 
 
    SELECT ID_EMPLEADO, CORREO_ELECTRONICO, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION, FECHA_INICIO, FECHA_NACIMIENTO, 
           CORREO_PRIMARIO, CORREO_SECUNDARIO, FECHA_CREACION, FECHA_ACTUALIZACION, USUARIO_CREADOR, USUARIO_ACTUALIZACION
    FROM   EMPLEADO 
    WHERE  (ID_EMPLEADO = @ID_EMPLEADO) 
END
GO

-------------------------------UPDATE
IF OBJECT_ID('SP_EMPLEADOS_UPDATE') IS NOT NULL
BEGIN 
DROP PROC SP_EMPLEADOS_UPDATE
END 
GO
CREATE PROC SP_EMPLEADOS_UPDATE
  @ID_EMPLEADO NUMERIC(12),
  @CORREO_ELECTRONICO VARCHAR(100),
  @PRIMER_NOMBRE VARCHAR(100),
  @SEGUNDO_NOMBRE VARCHAR(100),
  @PRIMER_APELLIDO VARCHAR(100),
  @SEGUNDO_APELLIDO VARCHAR(100),
  @DIRECCION VARCHAR(100),
  @FECHA_INICIO DATE,
  @FECHA_NACIMIENTO DATE,
  @CORREO_PRIMARIO VARCHAR(100),
  @CORREO_SECUNDARIO VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS 
BEGIN 
 
UPDATE EMPLEADO
SET 
    CORREO_ELECTRONICO = @CORREO_ELECTRONICO,
    PRIMER_NOMBRE = @PRIMER_NOMBRE,
    SEGUNDO_NOMBRE = @SEGUNDO_NOMBRE,
    PRIMER_APELLIDO = @PRIMER_APELLIDO,
    SEGUNDO_APELLIDO = @SEGUNDO_APELLIDO,
    DIRECCION = @DIRECCION,
    FECHA_INICIO = @FECHA_INICIO,
    FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
    CORREO_PRIMARIO = @CORREO_PRIMARIO,
    CORREO_SECUNDARIO = @CORREO_SECUNDARIO,
	  FECHA_CREACION = @FECHA_CREACION,
    FECHA_ACTUALIZACION = @FECHA_ACTUALIZACION,
    USUARIO_CREADOR = @USUARIO_CREADOR,
    USUARIO_ACTUALIZACION = @USUARIO_ACTUALIZACION
WHERE  ID_EMPLEADO = @ID_EMPLEADO
END
GO