IF OBJECT_ID('SP_PRESTAMOS_CREATE') IS NOT NULL
BEGIN 
DROP PROC SP_PRESTAMOS_CREATE 
END
GO
CREATE PROCEDURE SP_PRESTAMOS_CREATE
  @NUMERO_PRESTAMO NUMERIC(12),
  @ID_EMPLEADO NUMERIC(12),
  @PERIODO VARCHAR(100),
  @SALDO FLOAT,
  @EMPLEADO_AVAL VARCHAR(100),
  @MONTO FLOAT,
  @FECHA DATE,
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS
BEGIN
INSERT INTO PRESTAMOS  (
    NUMERO_PRESTAMO,
    ID_EMPLEADO,
    PERIODO,
    SALDO,
    EMPLEADO_AVAL,
    MONTO,
    FECHA,
	  FECHA_CREACION,
    FECHA_ACTUALIZACION,
    USUARIO_CREADOR,
    USUARIO_ACTUALIZACION)
  VALUES (
    @NUMERO_PRESTAMO,
    @ID_EMPLEADO,
    @PERIODO,
    @SALDO,
    @EMPLEADO_AVAL,
    @MONTO,
    @FECHA,
    @FECHA_CREACION,
    @FECHA_ACTUALIZACION,
    @USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION)
      
SELECT 
	  @ID_EMPLEADO = ID_EMPLEADO,
    @PERIODO = PERIODO,
    @SALDO = SALDO,
    @EMPLEADO_AVAL = EMPLEADO_AVAL,
    @MONTO = MONTO,
    @FECHA = FECHA,
	  @FECHA_CREACION = FECHA_CREACION,
    @FECHA_ACTUALIZACION = FECHA_ACTUALIZACION,
    @USUARIO_CREADOR = USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION = USUARIO_ACTUALIZACION
FROM PRESTAMOS 
WHERE  NUMERO_PRESTAMO = @NUMERO_PRESTAMO
END


------------------------------DELETE
IF OBJECT_ID('SP_PRESTAMOS_DELETE') IS NOT NULL
BEGIN 
DROP PROC SP_PRESTAMOS_DELETE
END 
GO
CREATE PROC SP_PRESTAMOS_DELETE 
    @NUMERO_PRESTAMO NUMERIC
AS 
BEGIN 
DELETE
FROM   PRESTAMOS
WHERE  NUMERO_PRESTAMO = @NUMERO_PRESTAMO
 
END
GO


---------------------------------READ
IF OBJECT_ID('SP_PRESTAMOS_READ') IS NOT NULL
BEGIN 
    DROP PROC SP_PRESTAMOS_READ
END 
GO
CREATE PROC SP_PRESTAMOS_READ
    @NUMERO_PRESTAMO NUMERIC
AS 
BEGIN 
 
    SELECT NUMERO_PRESTAMO, ID_EMPLEADO, PERIODO, SALDO, EMPLEADO_AVAL, MONTO, FECHA, FECHA_CREACION, FECHA_ACTUALIZACION, USUARIO_CREADOR, USUARIO_ACTUALIZACION
    FROM   PRESTAMOS  
    WHERE  (NUMERO_PRESTAMO = @NUMERO_PRESTAMO) 
END
GO

-------------------------------UPDATE
IF OBJECT_ID('SP_PRESTAMOS_UPDATE') IS NOT NULL
BEGIN 
DROP PROC SP_PRESTAMOS_UPDATE
END 
GO
CREATE PROC SP_PRESTAMOS_UPDATE
  @NUMERO_PRESTAMO NUMERIC(12),
  @ID_EMPLEADO NUMERIC(12),
  @PERIODO VARCHAR(100),
  @SALDO FLOAT,
  @EMPLEADO_AVAL VARCHAR(100),
  @MONTO FLOAT,
  @FECHA DATE,
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
  
AS 
BEGIN 
 
UPDATE PRESTAMOS
SET 
    ID_EMPLEADO = @ID_EMPLEADO,
    PERIODO = @PERIODO,
    SALDO = @SALDO,
    EMPLEADO_AVAL = @EMPLEADO_AVAL,
    MONTO = @MONTO,
    FECHA = @FECHA,
	  FECHA_CREACION = @FECHA_CREACION,
    FECHA_ACTUALIZACION = @FECHA_ACTUALIZACION,
    USUARIO_CREADOR = @USUARIO_CREADOR,
    USUARIO_ACTUALIZACION = @USUARIO_ACTUALIZACION
WHERE  NUMERO_PRESTAMO = @NUMERO_PRESTAMO
END
GO