IF OBJECT_ID('SP_PRIVILEGIOS_CREATE') IS NOT NULL
BEGIN 
DROP PROC SP_PRIVILEGIOS_CREATE 
END
GO
CREATE PROCEDURE SP_PRIVILEGIOS_CREATE
  @ID_PRIVILEGIO NUMERIC(12),
  @NOMBRE VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
AS
BEGIN
INSERT INTO PRIVILEGIOS  (
    ID_PRIVILEGIO,
	  NOMBRE,
	  FECHA_CREACION,
    FECHA_ACTUALIZACION,
    USUARIO_CREADOR,
    USUARIO_ACTUALIZACION)
  VALUES (
    @ID_PRIVILEGIO,
	  @NOMBRE,
    @FECHA_CREACION,
    @FECHA_ACTUALIZACION,
    @USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION)
      
SELECT 
	  @NOMBRE = NOMBRE,
	  @FECHA_CREACION = FECHA_CREACION,
    @FECHA_ACTUALIZACION = FECHA_ACTUALIZACION,
    @USUARIO_CREADOR = USUARIO_CREADOR,
    @USUARIO_ACTUALIZACION = USUARIO_ACTUALIZACION
FROM PRIVILEGIOS 
WHERE  ID_PRIVILEGIO = @ID_PRIVILEGIO
END


------------------------------DELETE
IF OBJECT_ID('SP_PRIVILEGIOS_DELETE') IS NOT NULL
BEGIN 
DROP PROC SP_PRIVILEGIOS_DELETE
END 
GO
CREATE PROC SP_PRIVILEGIOS_DELETE 
    @ID_PRIVILEGIO NUMERIC
AS 
BEGIN 
DELETE
FROM   PRIVILEGIOS
WHERE  ID_PRIVILEGIO = @ID_PRIVILEGIO
 
END
GO


---------------------------------READ
IF OBJECT_ID('SP_PRIVILEGIOS_READ') IS NOT NULL
BEGIN 
    DROP PROC SP_PRIVILEGIOS_READ
END 
GO
CREATE PROC SP_PRIVILEGIOS_READ
    @ID_PRIVILEGIO NUMERIC
AS 
BEGIN 
 
    SELECT ID_PRIVILEGIO, NOMBRE, FECHA_CREACION, FECHA_ACTUALIZACION, USUARIO_CREADOR, USUARIO_ACTUALIZACION
    FROM   PRIVILEGIOS  
    WHERE  (ID_PRIVILEGIO = @ID_PRIVILEGIO) 
END
GO

-------------------------------UPDATE
IF OBJECT_ID('SP_PRIVILEGIOS_UPDATE') IS NOT NULL
BEGIN 
DROP PROC SP_PRIVILEGIOS_UPDATE
END 
GO
CREATE PROC SP_PRIVILEGIOS_UPDATE
  @ID_PRIVILEGIO NUMERIC(12),
  @NOMBRE VARCHAR(100),
  @FECHA_CREACION DATE,
  @FECHA_ACTUALIZACION DATE,
  @USUARIO_CREADOR VARCHAR(100),
  @USUARIO_ACTUALIZACION VARCHAR(100)
  
AS 
BEGIN 
 
UPDATE PRIVILEGIOS
SET  
    NOMBRE = @NOMBRE,
	  FECHA_CREACION = @FECHA_CREACION,
    FECHA_ACTUALIZACION = @FECHA_ACTUALIZACION,
    USUARIO_CREADOR = @USUARIO_CREADOR,
    USUARIO_ACTUALIZACION = @USUARIO_ACTUALIZACION
WHERE  ID_PRIVILEGIO = @ID_PRIVILEGIO
END
GO