---------------INSERT
CREATE TRIGGER dbo.TRG_PRIVILEGIOS_AI on dbo.PRIVILEGIOS
FOR INSERT
AS
BEGIN

    INSERT INTO PRIVILEGIOS
    (
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
    )
  SELECT
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
  FROM PRIVILEGIOS AS p
END
go


---------------DELETE
create trigger dbo.TRG_PRIVILEGIOS_AD on dbo.PRIVILEGIOS
FOR DELETE
as
BEGIN

    INSERT INTO PRIVILEGIOS
    (
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
    )
  SELECT
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
  FROM PRIVILEGIOS AS p
END
go


---------------UPDATE
create trigger dbo.TRG_PRIVILEGIOS_AU on dbo.PRIVILEGIOS
FOR UPDATE
as
BEGIN

    INSERT INTO PRIVILEGIOS
    (
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
    )
  SELECT
      ID_PRIVILEGIO,
      NOMBRE,
      FECHA_CREACION,
      FECHA_ACTUALIZACION,
      USUARIO_CREADOR,
      USUARIO_ACTUALIZACION
  FROM PRIVILEGIOS AS p
END
go