---------------INSERT
CREATE TRIGGER dbo.TRG_PERSONA_EXTERNA_AI on dbo.PERSONA_EXTERNA
FOR INSERT
AS
BEGIN

    INSERT INTO PERSONA_EXTERNA
    (
      NEW.FECHA_CREACION,
      NEW.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM PERSONA_EXTERNA AS p
END
go


---------------DELETE
create trigger dbo.TRG_PERSONA_EXTERNA_AD on dbo.PERSONA_EXTERNA
FOR DELETE
as
BEGIN

    INSERT INTO PERSONA_EXTERNA
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM PERSONA_EXTERNA AS p
END
go


---------------UPDATE
create trigger dbo.TRG_PERSONA_EXTERNA_AU on dbo.PERSONA_EXTERNA
FOR UPDATE
as
BEGIN

    INSERT INTO PERSONA_EXTERNA
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      FECHA_ACTUALIZACION,
      USUARIO_ACTUALIZACION
  FROM PERSONA_EXTERNA AS p
END
go