---------------INSERT
CREATE TRIGGER dbo.TRG_PRESTAMOS_AI on dbo.PRESTAMOS
FOR INSERT
AS
BEGIN

    INSERT INTO PRESTAMOS
    (
      NEW.FECHA_CREACION,
      NEW.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM PRESTAMOS AS p
END
go


---------------DELETE
create trigger dbo.TRG_PRESTAMOS_AD on dbo.PRESTAMOS
FOR DELETE
as
BEGIN

    INSERT INTO PRESTAMOS
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM PRESTAMOS AS p
END
go


---------------UPDATE
create trigger dbo.TRG_PRESTAMOS_AU on dbo.PRESTAMOS
FOR UPDATE
as
BEGIN

    INSERT INTO PRESTAMOS
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      FECHA_ACTUALIZACION,
      USUARIO_ACTUALIZACION
  FROM PRESTAMOS AS p
END
go