---------------INSERT
CREATE TRIGGER dbo.TRG_EMPLEADO_AI on dbo.EMPLEADO
FOR INSERT
AS
BEGIN

    INSERT INTO EMPLEADO
    (
      NEW.FECHA_CREACION,
      NEW.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM EMPLEADO AS p
END
go


---------------DELETE
create trigger dbo.TRG_EMPLEADO_AD on dbo.EMPLEADO
FOR DELETE
as
BEGIN

    INSERT INTO EMPLEADO
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM EMPLEADO AS p
END
go


---------------UPDATE
create trigger dbo.TRG_EMPLEADO_AU on dbo.EMPLEADO
FOR UPDATE
as
BEGIN

    INSERT INTO EMPLEADO
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      FECHA_ACTUALIZACION,
      USUARIO_ACTUALIZACION
  FROM EMPLEADO AS p
END
go