---------------INSERT
CREATE TRIGGER dbo.TRG_USUARIOS_AI on dbo.USUARIOS
FOR INSERT
AS
BEGIN

    INSERT INTO USUARIOS
    (
      NEW.FECHA_CREACION,
      NEW.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM USUARIOS AS p
END
go


---------------DELETE
create trigger dbo.TRG_USUARIOS_AD on dbo.USUARIOS
FOR DELETE
as
BEGIN

    INSERT INTO USUARIOS
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      GETDATE(),
      USER
  FROM USUARIOS AS p
END
go


---------------UPDATE
create trigger dbo.TRG_USUARIOS_AU on dbo.USUARIOS
FOR UPDATE
as
BEGIN

    INSERT INTO USUARIOS
    (
      OLD.FECHA_CREACION,
      OLD.USUARIO_CREADOR
    )
  SELECT
      FECHA_ACTUALIZACION,
      USUARIO_ACTUALIZACION
  FROM USUARIOS AS p
END
go